/* This file has been generated by claude like
   the file Gameboy/Opcodes_table.c */

static uint8_t cb_rlc(Registers *cpu, uint8_t val) {
    uint8_t carry = (val & 0x80) >> 7;
    uint8_t result = (uint8_t)((val << 1) | carry);
    cpu->zf = (result == 0);
    cpu->nf = false;
    cpu->hf = false;
    cpu->cf = carry;
    return result;
}

static uint8_t cb_rrc(Registers *cpu, uint8_t val) {
    uint8_t carry = val & 0x01;
    uint8_t result = (uint8_t)((val >> 1) | (carry << 7));
    cpu->zf = (result == 0);
    cpu->nf = false;
    cpu->hf = false;
    cpu->cf = carry;
    return result;
}

static uint8_t cb_rl(Registers *cpu, uint8_t val) {
    uint8_t old_carry = cpu->cf ? 1 : 0;
    uint8_t new_carry = (val & 0x80) >> 7;
    uint8_t result = (uint8_t)((val << 1) | old_carry);
    cpu->zf = (result == 0);
    cpu->nf = false;
    cpu->hf = false;
    cpu->cf = new_carry;
    return result;
}

static uint8_t cb_rr(Registers *cpu, uint8_t val) {
    uint8_t old_carry = cpu->cf ? 1 : 0;
    uint8_t new_carry = val & 0x01;
    uint8_t result = (uint8_t)((val >> 1) | (old_carry << 7));
    cpu->zf = (result == 0);
    cpu->nf = false;
    cpu->hf = false;
    cpu->cf = new_carry;
    return result;
}

static uint8_t cb_sla(Registers *cpu, uint8_t val) {
    uint8_t carry = (val & 0x80) >> 7;
    uint8_t result = (uint8_t)(val << 1);
    cpu->zf = (result == 0);
    cpu->nf = false;
    cpu->hf = false;
    cpu->cf = carry;
    return result;
}

static uint8_t cb_sra(Registers *cpu, uint8_t val) {
    uint8_t carry = val & 0x01;
    uint8_t result = (uint8_t)((val >> 1) | (val & 0x80));
    cpu->zf = (result == 0);
    cpu->nf = false;
    cpu->hf = false;
    cpu->cf = carry;
    return result;
}

static uint8_t cb_swap(Registers *cpu, uint8_t val) {
    uint8_t result = (uint8_t)((val << 4) | (val >> 4));
    cpu->zf = (result == 0);
    cpu->nf = false;
    cpu->hf = false;
    cpu->cf = false;
    return result;
}

static uint8_t cb_srl(Registers *cpu, uint8_t val) {
    uint8_t carry = val & 0x01;
    uint8_t result = (uint8_t)(val >> 1);
    cpu->zf = (result == 0);
    cpu->nf = false;
    cpu->hf = false;
    cpu->cf = carry;
    return result;
}

static void cb_bit(Registers *cpu, uint8_t val, uint8_t bit) {
    cpu->zf = ((val & (1 << bit)) == 0);
    cpu->nf = false;
    cpu->hf = true;
}

static uint8_t cb_res(uint8_t val, uint8_t bit) {
    return (uint8_t)(val & ~(1 << bit));
}

static uint8_t cb_set(uint8_t val, uint8_t bit) {
    return (uint8_t)(val | (1 << bit));
}

uint8_t OprefCB(Registers *cpu, RAM *ram, uint8_t op_prefCB) {
    
 switch (op_prefCB) {

    /* ============================== RLC (0x00-0x07) ============================== */
    case 0x00: cpu->bc.hi = cb_rlc(cpu, cpu->bc.hi); cpu->pc += 2; return 8; // RLC B
    case 0x01: cpu->bc.lo = cb_rlc(cpu, cpu->bc.lo); cpu->pc += 2; return 8; // RLC C
    case 0x02: cpu->de.hi = cb_rlc(cpu, cpu->de.hi); cpu->pc += 2; return 8; // RLC D
    case 0x03: cpu->de.lo = cb_rlc(cpu, cpu->de.lo); cpu->pc += 2; return 8; // RLC E
    case 0x04: cpu->hl.hi = cb_rlc(cpu, cpu->hl.hi); cpu->pc += 2; return 8; // RLC H
    case 0x05: cpu->hl.lo = cb_rlc(cpu, cpu->hl.lo); cpu->pc += 2; return 8; // RLC L
    case 0x06: // RLC (HL)
        {
            uint8_t result = cb_rlc(cpu, read_memory8(ram, cpu->hl.value));
            write_memory8(ram, result, cpu->hl.value);
            cpu->pc += 2;
            return 16;
        }
    case 0x07: cpu->af.hi = cb_rlc(cpu, cpu->af.hi); cpu->pc += 2; return 8; // RLC A

    /* ============================== RRC (0x08-0x0F) ============================== */
    case 0x08: cpu->bc.hi = cb_rrc(cpu, cpu->bc.hi); cpu->pc += 2; return 8; // RRC B
    case 0x09: cpu->bc.lo = cb_rrc(cpu, cpu->bc.lo); cpu->pc += 2; return 8; // RRC C
    case 0x0A: cpu->de.hi = cb_rrc(cpu, cpu->de.hi); cpu->pc += 2; return 8; // RRC D
    case 0x0B: cpu->de.lo = cb_rrc(cpu, cpu->de.lo); cpu->pc += 2; return 8; // RRC E
    case 0x0C: cpu->hl.hi = cb_rrc(cpu, cpu->hl.hi); cpu->pc += 2; return 8; // RRC H
    case 0x0D: cpu->hl.lo = cb_rrc(cpu, cpu->hl.lo); cpu->pc += 2; return 8; // RRC L
    case 0x0E: // RRC (HL)
        {
            uint8_t result = cb_rrc(cpu, read_memory8(ram, cpu->hl.value));
            write_memory8(ram, result, cpu->hl.value);
            cpu->pc += 2;
            return 16;
        }
    case 0x0F: cpu->af.hi = cb_rrc(cpu, cpu->af.hi); cpu->pc += 2; return 8; // RRC A

    /* ============================== RL (0x10-0x17) ============================== */
    case 0x10: cpu->bc.hi = cb_rl(cpu, cpu->bc.hi); cpu->pc += 2; return 8; // RL B
    case 0x11: cpu->bc.lo = cb_rl(cpu, cpu->bc.lo); cpu->pc += 2; return 8; // RL C
    case 0x12: cpu->de.hi = cb_rl(cpu, cpu->de.hi); cpu->pc += 2; return 8; // RL D
    case 0x13: cpu->de.lo = cb_rl(cpu, cpu->de.lo); cpu->pc += 2; return 8; // RL E
    case 0x14: cpu->hl.hi = cb_rl(cpu, cpu->hl.hi); cpu->pc += 2; return 8; // RL H
    case 0x15: cpu->hl.lo = cb_rl(cpu, cpu->hl.lo); cpu->pc += 2; return 8; // RL L
    case 0x16: // RL (HL)
        {
            uint8_t result = cb_rl(cpu, read_memory8(ram, cpu->hl.value));
            write_memory8(ram, result, cpu->hl.value);
            cpu->pc += 2;
            return 16;
        }
    case 0x17: cpu->af.hi = cb_rl(cpu, cpu->af.hi); cpu->pc += 2; return 8; // RL A

    /* ============================== RR (0x18-0x1F) ============================== */
    case 0x18: cpu->bc.hi = cb_rr(cpu, cpu->bc.hi); cpu->pc += 2; return 8; // RR B
    case 0x19: cpu->bc.lo = cb_rr(cpu, cpu->bc.lo); cpu->pc += 2; return 8; // RR C
    case 0x1A: cpu->de.hi = cb_rr(cpu, cpu->de.hi); cpu->pc += 2; return 8; // RR D
    case 0x1B: cpu->de.lo = cb_rr(cpu, cpu->de.lo); cpu->pc += 2; return 8; // RR E
    case 0x1C: cpu->hl.hi = cb_rr(cpu, cpu->hl.hi); cpu->pc += 2; return 8; // RR H
    case 0x1D: cpu->hl.lo = cb_rr(cpu, cpu->hl.lo); cpu->pc += 2; return 8; // RR L
    case 0x1E: // RR (HL)
        {
            uint8_t result = cb_rr(cpu, read_memory8(ram, cpu->hl.value));
            write_memory8(ram, result, cpu->hl.value);
            cpu->pc += 2;
            return 16;
        }
    case 0x1F: cpu->af.hi = cb_rr(cpu, cpu->af.hi); cpu->pc += 2; return 8; // RR A

    /* ============================== SLA (0x20-0x27) ============================== */
    case 0x20: cpu->bc.hi = cb_sla(cpu, cpu->bc.hi); cpu->pc += 2; return 8; // SLA B
    case 0x21: cpu->bc.lo = cb_sla(cpu, cpu->bc.lo); cpu->pc += 2; return 8; // SLA C
    case 0x22: cpu->de.hi = cb_sla(cpu, cpu->de.hi); cpu->pc += 2; return 8; // SLA D
    case 0x23: cpu->de.lo = cb_sla(cpu, cpu->de.lo); cpu->pc += 2; return 8; // SLA E
    case 0x24: cpu->hl.hi = cb_sla(cpu, cpu->hl.hi); cpu->pc += 2; return 8; // SLA H
    case 0x25: cpu->hl.lo = cb_sla(cpu, cpu->hl.lo); cpu->pc += 2; return 8; // SLA L
    case 0x26: // SLA (HL)
        {
            uint8_t result = cb_sla(cpu, read_memory8(ram, cpu->hl.value));
            write_memory8(ram, result, cpu->hl.value);
            cpu->pc += 2;
            return 16;
        }
    case 0x27: cpu->af.hi = cb_sla(cpu, cpu->af.hi); cpu->pc += 2; return 8; // SLA A

    /* ============================== SRA (0x28-0x2F) ============================== */
    case 0x28: cpu->bc.hi = cb_sra(cpu, cpu->bc.hi); cpu->pc += 2; return 8; // SRA B
    case 0x29: cpu->bc.lo = cb_sra(cpu, cpu->bc.lo); cpu->pc += 2; return 8; // SRA C
    case 0x2A: cpu->de.hi = cb_sra(cpu, cpu->de.hi); cpu->pc += 2; return 8; // SRA D
    case 0x2B: cpu->de.lo = cb_sra(cpu, cpu->de.lo); cpu->pc += 2; return 8; // SRA E
    case 0x2C: cpu->hl.hi = cb_sra(cpu, cpu->hl.hi); cpu->pc += 2; return 8; // SRA H
    case 0x2D: cpu->hl.lo = cb_sra(cpu, cpu->hl.lo); cpu->pc += 2; return 8; // SRA L
    case 0x2E: // SRA (HL)
        {
            uint8_t result = cb_sra(cpu, read_memory8(ram, cpu->hl.value));
            write_memory8(ram, result, cpu->hl.value);
            cpu->pc += 2;
            return 16;
        }
    case 0x2F: cpu->af.hi = cb_sra(cpu, cpu->af.hi); cpu->pc += 2; return 8; // SRA A

    /* ============================== SWAP (0x30-0x37) ============================== */
    case 0x30: cpu->bc.hi = cb_swap(cpu, cpu->bc.hi); cpu->pc += 2; return 8; // SWAP B
    case 0x31: cpu->bc.lo = cb_swap(cpu, cpu->bc.lo); cpu->pc += 2; return 8; // SWAP C
    case 0x32: cpu->de.hi = cb_swap(cpu, cpu->de.hi); cpu->pc += 2; return 8; // SWAP D
    case 0x33: cpu->de.lo = cb_swap(cpu, cpu->de.lo); cpu->pc += 2; return 8; // SWAP E
    case 0x34: cpu->hl.hi = cb_swap(cpu, cpu->hl.hi); cpu->pc += 2; return 8; // SWAP H
    case 0x35: cpu->hl.lo = cb_swap(cpu, cpu->hl.lo); cpu->pc += 2; return 8; // SWAP L
    case 0x36: // SWAP (HL)
        {
            uint8_t result = cb_swap(cpu, read_memory8(ram, cpu->hl.value));
            write_memory8(ram, result, cpu->hl.value);
            cpu->pc += 2;
            return 16;
        }
    case 0x37: cpu->af.hi = cb_swap(cpu, cpu->af.hi); cpu->pc += 2; return 8; // SWAP A

    /* ============================== SRL (0x38-0x3F) ============================== */
    case 0x38: cpu->bc.hi = cb_srl(cpu, cpu->bc.hi); cpu->pc += 2; return 8; // SRL B
    case 0x39: cpu->bc.lo = cb_srl(cpu, cpu->bc.lo); cpu->pc += 2; return 8; // SRL C
    case 0x3A: cpu->de.hi = cb_srl(cpu, cpu->de.hi); cpu->pc += 2; return 8; // SRL D
    case 0x3B: cpu->de.lo = cb_srl(cpu, cpu->de.lo); cpu->pc += 2; return 8; // SRL E
    case 0x3C: cpu->hl.hi = cb_srl(cpu, cpu->hl.hi); cpu->pc += 2; return 8; // SRL H
    case 0x3D: cpu->hl.lo = cb_srl(cpu, cpu->hl.lo); cpu->pc += 2; return 8; // SRL L
    case 0x3E: // SRL (HL)
        {
            uint8_t result = cb_srl(cpu, read_memory8(ram, cpu->hl.value));
            write_memory8(ram, result, cpu->hl.value);
            cpu->pc += 2;
            return 16;
        }
    case 0x3F: cpu->af.hi = cb_srl(cpu, cpu->af.hi); cpu->pc += 2; return 8; // SRL A

    /* ============================== BIT 0 (0x40-0x47) ============================== */
    case 0x40: cb_bit(cpu, cpu->bc.hi, 0); cpu->pc += 2; return 8; // BIT 0,B
    case 0x41: cb_bit(cpu, cpu->bc.lo, 0); cpu->pc += 2; return 8; // BIT 0,C
    case 0x42: cb_bit(cpu, cpu->de.hi, 0); cpu->pc += 2; return 8; // BIT 0,D
    case 0x43: cb_bit(cpu, cpu->de.lo, 0); cpu->pc += 2; return 8; // BIT 0,E
    case 0x44: cb_bit(cpu, cpu->hl.hi, 0); cpu->pc += 2; return 8; // BIT 0,H
    case 0x45: cb_bit(cpu, cpu->hl.lo, 0); cpu->pc += 2; return 8; // BIT 0,L
    case 0x46: cb_bit(cpu, read_memory8(ram, cpu->hl.value), 0); cpu->pc += 2; return 12; // BIT 0,(HL)
    case 0x47: cb_bit(cpu, cpu->af.hi, 0); cpu->pc += 2; return 8; // BIT 0,A

    /* ============================== BIT 1 (0x48-0x4F) ============================== */
    case 0x48: cb_bit(cpu, cpu->bc.hi, 1); cpu->pc += 2; return 8; // BIT 1,B
    case 0x49: cb_bit(cpu, cpu->bc.lo, 1); cpu->pc += 2; return 8; // BIT 1,C
    case 0x4A: cb_bit(cpu, cpu->de.hi, 1); cpu->pc += 2; return 8; // BIT 1,D
    case 0x4B: cb_bit(cpu, cpu->de.lo, 1); cpu->pc += 2; return 8; // BIT 1,E
    case 0x4C: cb_bit(cpu, cpu->hl.hi, 1); cpu->pc += 2; return 8; // BIT 1,H
    case 0x4D: cb_bit(cpu, cpu->hl.lo, 1); cpu->pc += 2; return 8; // BIT 1,L
    case 0x4E: cb_bit(cpu, read_memory8(ram, cpu->hl.value), 1); cpu->pc += 2; return 12; // BIT 1,(HL)
    case 0x4F: cb_bit(cpu, cpu->af.hi, 1); cpu->pc += 2; return 8; // BIT 1,A

    /* ============================== BIT 2 (0x50-0x57) ============================== */
    case 0x50: cb_bit(cpu, cpu->bc.hi, 2); cpu->pc += 2; return 8; // BIT 2,B
    case 0x51: cb_bit(cpu, cpu->bc.lo, 2); cpu->pc += 2; return 8; // BIT 2,C
    case 0x52: cb_bit(cpu, cpu->de.hi, 2); cpu->pc += 2; return 8; // BIT 2,D
    case 0x53: cb_bit(cpu, cpu->de.lo, 2); cpu->pc += 2; return 8; // BIT 2,E
    case 0x54: cb_bit(cpu, cpu->hl.hi, 2); cpu->pc += 2; return 8; // BIT 2,H
    case 0x55: cb_bit(cpu, cpu->hl.lo, 2); cpu->pc += 2; return 8; // BIT 2,L
    case 0x56: cb_bit(cpu, read_memory8(ram, cpu->hl.value), 2); cpu->pc += 2; return 12; // BIT 2,(HL)
    case 0x57: cb_bit(cpu, cpu->af.hi, 2); cpu->pc += 2; return 8; // BIT 2,A

    /* ============================== BIT 3 (0x58-0x5F) ============================== */
    case 0x58: cb_bit(cpu, cpu->bc.hi, 3); cpu->pc += 2; return 8; // BIT 3,B
    case 0x59: cb_bit(cpu, cpu->bc.lo, 3); cpu->pc += 2; return 8; // BIT 3,C
    case 0x5A: cb_bit(cpu, cpu->de.hi, 3); cpu->pc += 2; return 8; // BIT 3,D
    case 0x5B: cb_bit(cpu, cpu->de.lo, 3); cpu->pc += 2; return 8; // BIT 3,E
    case 0x5C: cb_bit(cpu, cpu->hl.hi, 3); cpu->pc += 2; return 8; // BIT 3,H
    case 0x5D: cb_bit(cpu, cpu->hl.lo, 3); cpu->pc += 2; return 8; // BIT 3,L
    case 0x5E: cb_bit(cpu, read_memory8(ram, cpu->hl.value), 3); cpu->pc += 2; return 12; // BIT 3,(HL)
    case 0x5F: cb_bit(cpu, cpu->af.hi, 3); cpu->pc += 2; return 8; // BIT 3,A

    /* ============================== BIT 4 (0x60-0x67) ============================== */
    case 0x60: cb_bit(cpu, cpu->bc.hi, 4); cpu->pc += 2; return 8; // BIT 4,B
    case 0x61: cb_bit(cpu, cpu->bc.lo, 4); cpu->pc += 2; return 8; // BIT 4,C
    case 0x62: cb_bit(cpu, cpu->de.hi, 4); cpu->pc += 2; return 8; // BIT 4,D
    case 0x63: cb_bit(cpu, cpu->de.lo, 4); cpu->pc += 2; return 8; // BIT 4,E
    case 0x64: cb_bit(cpu, cpu->hl.hi, 4); cpu->pc += 2; return 8; // BIT 4,H
    case 0x65: cb_bit(cpu, cpu->hl.lo, 4); cpu->pc += 2; return 8; // BIT 4,L
    case 0x66: cb_bit(cpu, read_memory8(ram, cpu->hl.value), 4); cpu->pc += 2; return 12; // BIT 4,(HL)
    case 0x67: cb_bit(cpu, cpu->af.hi, 4); cpu->pc += 2; return 8; // BIT 4,A

    /* ============================== BIT 5 (0x68-0x6F) ============================== */
    case 0x68: cb_bit(cpu, cpu->bc.hi, 5); cpu->pc += 2; return 8; // BIT 5,B
    case 0x69: cb_bit(cpu, cpu->bc.lo, 5); cpu->pc += 2; return 8; // BIT 5,C
    case 0x6A: cb_bit(cpu, cpu->de.hi, 5); cpu->pc += 2; return 8; // BIT 5,D
    case 0x6B: cb_bit(cpu, cpu->de.lo, 5); cpu->pc += 2; return 8; // BIT 5,E
    case 0x6C: cb_bit(cpu, cpu->hl.hi, 5); cpu->pc += 2; return 8; // BIT 5,H
    case 0x6D: cb_bit(cpu, cpu->hl.lo, 5); cpu->pc += 2; return 8; // BIT 5,L
    case 0x6E: cb_bit(cpu, read_memory8(ram, cpu->hl.value), 5); cpu->pc += 2; return 12; // BIT 5,(HL)
    case 0x6F: cb_bit(cpu, cpu->af.hi, 5); cpu->pc += 2; return 8; // BIT 5,A

    /* ============================== BIT 6 (0x70-0x77) ============================== */
    case 0x70: cb_bit(cpu, cpu->bc.hi, 6); cpu->pc += 2; return 8; // BIT 6,B
    case 0x71: cb_bit(cpu, cpu->bc.lo, 6); cpu->pc += 2; return 8; // BIT 6,C
    case 0x72: cb_bit(cpu, cpu->de.hi, 6); cpu->pc += 2; return 8; // BIT 6,D
    case 0x73: cb_bit(cpu, cpu->de.lo, 6); cpu->pc += 2; return 8; // BIT 6,E
    case 0x74: cb_bit(cpu, cpu->hl.hi, 6); cpu->pc += 2; return 8; // BIT 6,H
    case 0x75: cb_bit(cpu, cpu->hl.lo, 6); cpu->pc += 2; return 8; // BIT 6,L
    case 0x76: cb_bit(cpu, read_memory8(ram, cpu->hl.value), 6); cpu->pc += 2; return 12; // BIT 6,(HL)
    case 0x77: cb_bit(cpu, cpu->af.hi, 6); cpu->pc += 2; return 8; // BIT 6,A

    /* ============================== BIT 7 (0x78-0x7F) ============================== */
    case 0x78: cb_bit(cpu, cpu->bc.hi, 7); cpu->pc += 2; return 8; // BIT 7,B
    case 0x79: cb_bit(cpu, cpu->bc.lo, 7); cpu->pc += 2; return 8; // BIT 7,C
    case 0x7A: cb_bit(cpu, cpu->de.hi, 7); cpu->pc += 2; return 8; // BIT 7,D
    case 0x7B: cb_bit(cpu, cpu->de.lo, 7); cpu->pc += 2; return 8; // BIT 7,E
    case 0x7C:
        cb_bit(cpu, cpu->hl.hi, 7); // BIT 7,H
        cpu->pc += 2;
        return 8;
    case 0x7D: cb_bit(cpu, cpu->hl.lo, 7); cpu->pc += 2; return 8; // BIT 7,L
    case 0x7E: cb_bit(cpu, read_memory8(ram, cpu->hl.value), 7); cpu->pc += 2; return 12; // BIT 7,(HL)
    case 0x7F: cb_bit(cpu, cpu->af.hi, 7); cpu->pc += 2; return 8; // BIT 7,A

    /* ============================== RES 0 (0x80-0x87) ============================== */
    case 0x80: cpu->bc.hi = cb_res(cpu->bc.hi, 0); cpu->pc += 2; return 8; // RES 0,B
    case 0x81: cpu->bc.lo = cb_res(cpu->bc.lo, 0); cpu->pc += 2; return 8; // RES 0,C
    case 0x82: cpu->de.hi = cb_res(cpu->de.hi, 0); cpu->pc += 2; return 8; // RES 0,D
    case 0x83: cpu->de.lo = cb_res(cpu->de.lo, 0); cpu->pc += 2; return 8; // RES 0,E
    case 0x84: cpu->hl.hi = cb_res(cpu->hl.hi, 0); cpu->pc += 2; return 8; // RES 0,H
    case 0x85: cpu->hl.lo = cb_res(cpu->hl.lo, 0); cpu->pc += 2; return 8; // RES 0,L
    case 0x86: write_memory8(ram, cb_res(read_memory8(ram, cpu->hl.value), 0), cpu->hl.value); cpu->pc += 2; return 16; // RES 0,(HL)
    case 0x87: cpu->af.hi = cb_res(cpu->af.hi, 0); cpu->pc += 2; return 8; // RES 0,A

    /* ============================== RES 1 (0x88-0x8F) ============================== */
    case 0x88: cpu->bc.hi = cb_res(cpu->bc.hi, 1); cpu->pc += 2; return 8; // RES 1,B
    case 0x89: cpu->bc.lo = cb_res(cpu->bc.lo, 1); cpu->pc += 2; return 8; // RES 1,C
    case 0x8A: cpu->de.hi = cb_res(cpu->de.hi, 1); cpu->pc += 2; return 8; // RES 1,D
    case 0x8B: cpu->de.lo = cb_res(cpu->de.lo, 1); cpu->pc += 2; return 8; // RES 1,E
    case 0x8C: cpu->hl.hi = cb_res(cpu->hl.hi, 1); cpu->pc += 2; return 8; // RES 1,H
    case 0x8D: cpu->hl.lo = cb_res(cpu->hl.lo, 1); cpu->pc += 2; return 8; // RES 1,L
    case 0x8E: write_memory8(ram, cb_res(read_memory8(ram, cpu->hl.value), 1), cpu->hl.value); cpu->pc += 2; return 16; // RES 1,(HL)
    case 0x8F: cpu->af.hi = cb_res(cpu->af.hi, 1); cpu->pc += 2; return 8; // RES 1,A

    /* ============================== RES 2 (0x90-0x97) ============================== */
    case 0x90: cpu->bc.hi = cb_res(cpu->bc.hi, 2); cpu->pc += 2; return 8; // RES 2,B
    case 0x91: cpu->bc.lo = cb_res(cpu->bc.lo, 2); cpu->pc += 2; return 8; // RES 2,C
    case 0x92: cpu->de.hi = cb_res(cpu->de.hi, 2); cpu->pc += 2; return 8; // RES 2,D
    case 0x93: cpu->de.lo = cb_res(cpu->de.lo, 2); cpu->pc += 2; return 8; // RES 2,E
    case 0x94: cpu->hl.hi = cb_res(cpu->hl.hi, 2); cpu->pc += 2; return 8; // RES 2,H
    case 0x95: cpu->hl.lo = cb_res(cpu->hl.lo, 2); cpu->pc += 2; return 8; // RES 2,L
    case 0x96: write_memory8(ram, cb_res(read_memory8(ram, cpu->hl.value), 2), cpu->hl.value); cpu->pc += 2; return 16; // RES 2,(HL)
    case 0x97: cpu->af.hi = cb_res(cpu->af.hi, 2); cpu->pc += 2; return 8; // RES 2,A

    /* ============================== RES 3 (0x98-0x9F) ============================== */
    case 0x98: cpu->bc.hi = cb_res(cpu->bc.hi, 3); cpu->pc += 2; return 8; // RES 3,B
    case 0x99: cpu->bc.lo = cb_res(cpu->bc.lo, 3); cpu->pc += 2; return 8; // RES 3,C
    case 0x9A: cpu->de.hi = cb_res(cpu->de.hi, 3); cpu->pc += 2; return 8; // RES 3,D
    case 0x9B: cpu->de.lo = cb_res(cpu->de.lo, 3); cpu->pc += 2; return 8; // RES 3,E
    case 0x9C: cpu->hl.hi = cb_res(cpu->hl.hi, 3); cpu->pc += 2; return 8; // RES 3,H
    case 0x9D: cpu->hl.lo = cb_res(cpu->hl.lo, 3); cpu->pc += 2; return 8; // RES 3,L
    case 0x9E: write_memory8(ram, cb_res(read_memory8(ram, cpu->hl.value), 3), cpu->hl.value); cpu->pc += 2; return 16; // RES 3,(HL)
    case 0x9F: cpu->af.hi = cb_res(cpu->af.hi, 3); cpu->pc += 2; return 8; // RES 3,A

    /* ============================== RES 4 (0xA0-0xA7) ============================== */
    case 0xA0: cpu->bc.hi = cb_res(cpu->bc.hi, 4); cpu->pc += 2; return 8; // RES 4,B
    case 0xA1: cpu->bc.lo = cb_res(cpu->bc.lo, 4); cpu->pc += 2; return 8; // RES 4,C
    case 0xA2: cpu->de.hi = cb_res(cpu->de.hi, 4); cpu->pc += 2; return 8; // RES 4,D
    case 0xA3: cpu->de.lo = cb_res(cpu->de.lo, 4); cpu->pc += 2; return 8; // RES 4,E
    case 0xA4: cpu->hl.hi = cb_res(cpu->hl.hi, 4); cpu->pc += 2; return 8; // RES 4,H
    case 0xA5: cpu->hl.lo = cb_res(cpu->hl.lo, 4); cpu->pc += 2; return 8; // RES 4,L
    case 0xA6: write_memory8(ram, cb_res(read_memory8(ram, cpu->hl.value), 4), cpu->hl.value); cpu->pc += 2; return 16; // RES 4,(HL)
    case 0xA7: cpu->af.hi = cb_res(cpu->af.hi, 4); cpu->pc += 2; return 8; // RES 4,A

    /* ============================== RES 5 (0xA8-0xAF) ============================== */
    case 0xA8: cpu->bc.hi = cb_res(cpu->bc.hi, 5); cpu->pc += 2; return 8; // RES 5,B
    case 0xA9: cpu->bc.lo = cb_res(cpu->bc.lo, 5); cpu->pc += 2; return 8; // RES 5,C
    case 0xAA: cpu->de.hi = cb_res(cpu->de.hi, 5); cpu->pc += 2; return 8; // RES 5,D
    case 0xAB: cpu->de.lo = cb_res(cpu->de.lo, 5); cpu->pc += 2; return 8; // RES 5,E
    case 0xAC: cpu->hl.hi = cb_res(cpu->hl.hi, 5); cpu->pc += 2; return 8; // RES 5,H
    case 0xAD: cpu->hl.lo = cb_res(cpu->hl.lo, 5); cpu->pc += 2; return 8; // RES 5,L
    case 0xAE: write_memory8(ram, cb_res(read_memory8(ram, cpu->hl.value), 5), cpu->hl.value); cpu->pc += 2; return 16; // RES 5,(HL)
    case 0xAF: cpu->af.hi = cb_res(cpu->af.hi, 5); cpu->pc += 2; return 8; // RES 5,A

    /* ============================== RES 6 (0xB0-0xB7) ============================== */
    case 0xB0: cpu->bc.hi = cb_res(cpu->bc.hi, 6); cpu->pc += 2; return 8; // RES 6,B
    case 0xB1: cpu->bc.lo = cb_res(cpu->bc.lo, 6); cpu->pc += 2; return 8; // RES 6,C
    case 0xB2: cpu->de.hi = cb_res(cpu->de.hi, 6); cpu->pc += 2; return 8; // RES 6,D
    case 0xB3: cpu->de.lo = cb_res(cpu->de.lo, 6); cpu->pc += 2; return 8; // RES 6,E
    case 0xB4: cpu->hl.hi = cb_res(cpu->hl.hi, 6); cpu->pc += 2; return 8; // RES 6,H
    case 0xB5: cpu->hl.lo = cb_res(cpu->hl.lo, 6); cpu->pc += 2; return 8; // RES 6,L
    case 0xB6: write_memory8(ram, cb_res(read_memory8(ram, cpu->hl.value), 6), cpu->hl.value); cpu->pc += 2; return 16; // RES 6,(HL)
    case 0xB7: cpu->af.hi = cb_res(cpu->af.hi, 6); cpu->pc += 2; return 8; // RES 6,A

    /* ============================== RES 7 (0xB8-0xBF) ============================== */
    case 0xB8: cpu->bc.hi = cb_res(cpu->bc.hi, 7); cpu->pc += 2; return 8; // RES 7,B
    case 0xB9: cpu->bc.lo = cb_res(cpu->bc.lo, 7); cpu->pc += 2; return 8; // RES 7,C
    case 0xBA: cpu->de.hi = cb_res(cpu->de.hi, 7); cpu->pc += 2; return 8; // RES 7,D
    case 0xBB: cpu->de.lo = cb_res(cpu->de.lo, 7); cpu->pc += 2; return 8; // RES 7,E
    case 0xBC: cpu->hl.hi = cb_res(cpu->hl.hi, 7); cpu->pc += 2; return 8; // RES 7,H
    case 0xBD: cpu->hl.lo = cb_res(cpu->hl.lo, 7); cpu->pc += 2; return 8; // RES 7,L
    case 0xBE: write_memory8(ram, cb_res(read_memory8(ram, cpu->hl.value), 7), cpu->hl.value); cpu->pc += 2; return 16; // RES 7,(HL)
    case 0xBF: cpu->af.hi = cb_res(cpu->af.hi, 7); cpu->pc += 2; return 8; // RES 7,A

    /* ============================== SET 0 (0xC0-0xC7) ============================== */
    case 0xC0: cpu->bc.hi = cb_set(cpu->bc.hi, 0); cpu->pc += 2; return 8; // SET 0,B
    case 0xC1: cpu->bc.lo = cb_set(cpu->bc.lo, 0); cpu->pc += 2; return 8; // SET 0,C
    case 0xC2: cpu->de.hi = cb_set(cpu->de.hi, 0); cpu->pc += 2; return 8; // SET 0,D
    case 0xC3: cpu->de.lo = cb_set(cpu->de.lo, 0); cpu->pc += 2; return 8; // SET 0,E
    case 0xC4: cpu->hl.hi = cb_set(cpu->hl.hi, 0); cpu->pc += 2; return 8; // SET 0,H
    case 0xC5: cpu->hl.lo = cb_set(cpu->hl.lo, 0); cpu->pc += 2; return 8; // SET 0,L
    case 0xC6: write_memory8(ram, cb_set(read_memory8(ram, cpu->hl.value), 0), cpu->hl.value); cpu->pc += 2; return 16; // SET 0,(HL)
    case 0xC7: cpu->af.hi = cb_set(cpu->af.hi, 0); cpu->pc += 2; return 8; // SET 0,A

    /* ============================== SET 1 (0xC8-0xCF) ============================== */
    case 0xC8: cpu->bc.hi = cb_set(cpu->bc.hi, 1); cpu->pc += 2; return 8; // SET 1,B
    case 0xC9: cpu->bc.lo = cb_set(cpu->bc.lo, 1); cpu->pc += 2; return 8; // SET 1,C
    case 0xCA: cpu->de.hi = cb_set(cpu->de.hi, 1); cpu->pc += 2; return 8; // SET 1,D
    case 0xCB: cpu->de.lo = cb_set(cpu->de.lo, 1); cpu->pc += 2; return 8; // SET 1,E
    case 0xCC: cpu->hl.hi = cb_set(cpu->hl.hi, 1); cpu->pc += 2; return 8; // SET 1,H
    case 0xCD: cpu->hl.lo = cb_set(cpu->hl.lo, 1); cpu->pc += 2; return 8; // SET 1,L
    case 0xCE: write_memory8(ram, cb_set(read_memory8(ram, cpu->hl.value), 1), cpu->hl.value); cpu->pc += 2; return 16; // SET 1,(HL)
    case 0xCF: cpu->af.hi = cb_set(cpu->af.hi, 1); cpu->pc += 2; return 8; // SET 1,A

    /* ============================== SET 2 (0xD0-0xD7) ============================== */
    case 0xD0: cpu->bc.hi = cb_set(cpu->bc.hi, 2); cpu->pc += 2; return 8; // SET 2,B
    case 0xD1: cpu->bc.lo = cb_set(cpu->bc.lo, 2); cpu->pc += 2; return 8; // SET 2,C
    case 0xD2: cpu->de.hi = cb_set(cpu->de.hi, 2); cpu->pc += 2; return 8; // SET 2,D
    case 0xD3: cpu->de.lo = cb_set(cpu->de.lo, 2); cpu->pc += 2; return 8; // SET 2,E
    case 0xD4: cpu->hl.hi = cb_set(cpu->hl.hi, 2); cpu->pc += 2; return 8; // SET 2,H
    case 0xD5: cpu->hl.lo = cb_set(cpu->hl.lo, 2); cpu->pc += 2; return 8; // SET 2,L
    case 0xD6: write_memory8(ram, cb_set(read_memory8(ram, cpu->hl.value), 2), cpu->hl.value); cpu->pc += 2; return 16; // SET 2,(HL)
    case 0xD7: cpu->af.hi = cb_set(cpu->af.hi, 2); cpu->pc += 2; return 8; // SET 2,A

    /* ============================== SET 3 (0xD8-0xDF) ============================== */
    case 0xD8: cpu->bc.hi = cb_set(cpu->bc.hi, 3); cpu->pc += 2; return 8; // SET 3,B
    case 0xD9: cpu->bc.lo = cb_set(cpu->bc.lo, 3); cpu->pc += 2; return 8; // SET 3,C
    case 0xDA: cpu->de.hi = cb_set(cpu->de.hi, 3); cpu->pc += 2; return 8; // SET 3,D
    case 0xDB: cpu->de.lo = cb_set(cpu->de.lo, 3); cpu->pc += 2; return 8; // SET 3,E
    case 0xDC: cpu->hl.hi = cb_set(cpu->hl.hi, 3); cpu->pc += 2; return 8; // SET 3,H
    case 0xDD: cpu->hl.lo = cb_set(cpu->hl.lo, 3); cpu->pc += 2; return 8; // SET 3,L
    case 0xDE: write_memory8(ram, cb_set(read_memory8(ram, cpu->hl.value), 3), cpu->hl.value); cpu->pc += 2; return 16; // SET 3,(HL)
    case 0xDF: cpu->af.hi = cb_set(cpu->af.hi, 3); cpu->pc += 2; return 8; // SET 3,A

    /* ============================== SET 4 (0xE0-0xE7) ============================== */
    case 0xE0: cpu->bc.hi = cb_set(cpu->bc.hi, 4); cpu->pc += 2; return 8; // SET 4,B
    case 0xE1: cpu->bc.lo = cb_set(cpu->bc.lo, 4); cpu->pc += 2; return 8; // SET 4,C
    case 0xE2: cpu->de.hi = cb_set(cpu->de.hi, 4); cpu->pc += 2; return 8; // SET 4,D
    case 0xE3: cpu->de.lo = cb_set(cpu->de.lo, 4); cpu->pc += 2; return 8; // SET 4,E
    case 0xE4: cpu->hl.hi = cb_set(cpu->hl.hi, 4); cpu->pc += 2; return 8; // SET 4,H
    case 0xE5: cpu->hl.lo = cb_set(cpu->hl.lo, 4); cpu->pc += 2; return 8; // SET 4,L
    case 0xE6: write_memory8(ram, cb_set(read_memory8(ram, cpu->hl.value), 4), cpu->hl.value); cpu->pc += 2; return 16; // SET 4,(HL)
    case 0xE7: cpu->af.hi = cb_set(cpu->af.hi, 4); cpu->pc += 2; return 8; // SET 4,A

    /* ============================== SET 5 (0xE8-0xEF) ============================== */
    case 0xE8: cpu->bc.hi = cb_set(cpu->bc.hi, 5); cpu->pc += 2; return 8; // SET 5,B
    case 0xE9: cpu->bc.lo = cb_set(cpu->bc.lo, 5); cpu->pc += 2; return 8; // SET 5,C
    case 0xEA: cpu->de.hi = cb_set(cpu->de.hi, 5); cpu->pc += 2; return 8; // SET 5,D
    case 0xEB: cpu->de.lo = cb_set(cpu->de.lo, 5); cpu->pc += 2; return 8; // SET 5,E
    case 0xEC: cpu->hl.hi = cb_set(cpu->hl.hi, 5); cpu->pc += 2; return 8; // SET 5,H
    case 0xED: cpu->hl.lo = cb_set(cpu->hl.lo, 5); cpu->pc += 2; return 8; // SET 5,L
    case 0xEE: write_memory8(ram, cb_set(read_memory8(ram, cpu->hl.value), 5), cpu->hl.value); cpu->pc += 2; return 16; // SET 5,(HL)
    case 0xEF: cpu->af.hi = cb_set(cpu->af.hi, 5); cpu->pc += 2; return 8; // SET 5,A

    /* ============================== SET 6 (0xF0-0xF7) ============================== */
    case 0xF0: cpu->bc.hi = cb_set(cpu->bc.hi, 6); cpu->pc += 2; return 8; // SET 6,B
    case 0xF1: cpu->bc.lo = cb_set(cpu->bc.lo, 6); cpu->pc += 2; return 8; // SET 6,C
    case 0xF2: cpu->de.hi = cb_set(cpu->de.hi, 6); cpu->pc += 2; return 8; // SET 6,D
    case 0xF3: cpu->de.lo = cb_set(cpu->de.lo, 6); cpu->pc += 2; return 8; // SET 6,E
    case 0xF4: cpu->hl.hi = cb_set(cpu->hl.hi, 6); cpu->pc += 2; return 8; // SET 6,H
    case 0xF5: cpu->hl.lo = cb_set(cpu->hl.lo, 6); cpu->pc += 2; return 8; // SET 6,L
    case 0xF6: write_memory8(ram, cb_set(read_memory8(ram, cpu->hl.value), 6), cpu->hl.value); cpu->pc += 2; return 16; // SET 6,(HL)
    case 0xF7: cpu->af.hi = cb_set(cpu->af.hi, 6); cpu->pc += 2; return 8; // SET 6,A

    /* ============================== SET 7 (0xF8-0xFF) ============================== */
    case 0xF8: cpu->bc.hi = cb_set(cpu->bc.hi, 7); cpu->pc += 2; return 8; // SET 7,B
    case 0xF9: cpu->bc.lo = cb_set(cpu->bc.lo, 7); cpu->pc += 2; return 8; // SET 7,C
    case 0xFA: cpu->de.hi = cb_set(cpu->de.hi, 7); cpu->pc += 2; return 8; // SET 7,D
    case 0xFB: cpu->de.lo = cb_set(cpu->de.lo, 7); cpu->pc += 2; return 8; // SET 7,E
    case 0xFC: cpu->hl.hi = cb_set(cpu->hl.hi, 7); cpu->pc += 2; return 8; // SET 7,H
    case 0xFD: cpu->hl.lo = cb_set(cpu->hl.lo, 7); cpu->pc += 2; return 8; // SET 7,L
    case 0xFE: write_memory8(ram, cb_set(read_memory8(ram, cpu->hl.value), 7), cpu->hl.value); cpu->pc += 2; return 16; // SET 7,(HL)
    case 0xFF: cpu->af.hi = cb_set(cpu->af.hi, 7); cpu->pc += 2; return 8; // SET 7,A

    default:
        printf("-CB Opcode not found : %02X\n", op_prefCB);
        return 0;
    }
}
